# Generated by Django 5.1.7 on 2025-03-25 12:07

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('main_img', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality='80', scale=0.5, size=[988, 800], upload_to='main/%Y/%m')),
            ],
            options={
                'verbose_name': 'Asosiy',
                'verbose_name_plural': 'Asosiy',
                'db_table': 'Asosiy',
            },
        ),
    ]
