# Generated by Django 5.1.7 on 2025-03-25 12:10

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='main_img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality='75', scale=0.5, size=[988, 800], upload_to='main/%Y/%m'),
        ),
    ]
