# Generated by Django 5.1.7 on 2025-03-25 12:32

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_mainpage_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnoX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[700, 473], upload_to='main/%Y/%m')),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=256)),
                ('lesson_duration', models.CharField(max_length=256)),
                ('lesson_days', models.CharField(max_length=256)),
                ('age_limit', models.CharField(max_length=256)),
                ('requirements', models.TextField()),
            ],
            options={
                'verbose_name': 'Innox',
                'verbose_name_plural': 'Innox',
                'db_table': 'Innox',
            },
        ),
    ]
