# Generated by Django 5.1.7 on 2025-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('facebook', models.CharField(max_length=256)),
                ('instagram', models.CharField(max_length=256)),
                ('telegram', models.CharField(max_length=256)),
                ('github', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Mentors',
                'verbose_name_plural': 'Mentors',
                'db_table': 'Mentors',
            },
        ),
    ]
