# Generated by Django 5.1.7 on 2025-03-25 12:51

import django.utils.timezone
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=django.utils.timezone.now, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[405, 500], upload_to='mentors/%Y/%m'),
            preserve_default=False,
        ),
    ]
