# Generated by Django 5.1.7 on 2025-03-25 15:11

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyTexnopark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='main/%Y/%m')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'WhyTexnopark',
                'verbose_name_plural': 'WhyTexnopark',
                'db_table': 'WhyTexnopark',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[550, 300], upload_to='news/%Y/%m'),
        ),
    ]
