# Generated by Django 5.1.7 on 2025-03-25 15:18

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_whytexnopark_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[446, 380], upload_to='StudentProject/%Y/%m')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'StudentProject',
                'verbose_name_plural': 'StudentProject',
                'db_table': 'StudentProject',
            },
        ),
    ]
