# Generated by Django 5.1.7 on 2025-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_studentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
                'db_table': 'Questions',
            },
        ),
    ]
