# Generated by Django 5.1.7 on 2025-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
