# Generated by Django 5.1.7 on 2025-03-25 18:32

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_question_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[550, 650], upload_to='SliderContent/%Y/%m')),
                ('small_top_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[550, 315], upload_to='SliderContent/%Y/%m')),
                ('small_bottom_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[550, 315], upload_to='SliderContent/%Y/%m')),
            ],
            options={
                'verbose_name': 'SliderContent',
                'verbose_name_plural': 'SliderContent',
                'db_table': 'SliderContent',
            },
        ),
    ]
