# Generated by Django 5.1.6 on 2025-03-25 18:46

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_slidercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidercompany',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='slidercompany',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[350, 80], upload_to='SliderCompany/%Y/%m'),
        ),
    ]
