# Generated by Django 5.1.6 on 2025-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_slidercompany_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('address', models.TextField()),
                ('facebook', models.CharField(max_length=256)),
                ('instagram', models.CharField(max_length=256)),
                ('telegram', models.CharField(max_length=256)),
                ('mail', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
                'db_table': 'Footer',
            },
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='icon',
        ),
    ]
