# Generated by Django 5.1.6 on 2025-03-25 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_footer_remove_mainpage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='icon',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
