# Generated by Django 5.1.6 on 2025-03-25 19:20

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_mainpage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[700, 473], upload_to='main/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='innox',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[700, 473], upload_to='main/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='main_img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[988, 800], upload_to='main/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[405, 500], upload_to='mentors/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[550, 300], upload_to='news/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='slidercompany',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='big_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[550, 650], upload_to='SliderContent/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='small_bottom_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[550, 315], upload_to='SliderContent/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='small_top_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[550, 315], upload_to='SliderContent/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[446, 380], upload_to='StudentProject/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='whytexnopark',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=95, scale=None, size=[1920, 1080], upload_to='main/%Y/%m'),
        ),
    ]
