# Generated by Django 5.1.6 on 2025-03-25 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_aboutus_image_alter_innox_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'purpose',
                'verbose_name_plural': 'purpose',
                'db_table': 'purpose',
            },
        ),
        migrations.CreateModel(
            name='StartAppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'startappcategory',
                'verbose_name_plural': 'startappcategories',
                'db_table': 'startappcategory',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=256)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('startap_name', models.CharField(max_length=256)),
                ('another_category', models.CharField(max_length=256, null=True)),
                ('about_startapp', models.CharField(max_length=256)),
                ('about_team', models.CharField(max_length=256)),
                ('project_prototype', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=256)),
                ('startap_image', models.FileField(upload_to='startap_image/%Y/%m')),
                ('presentation', models.FileField(upload_to='presentation/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['pptx', 'pdf'])], verbose_name='presentation')),
                ('agree', models.BooleanField(default=False)),
                ('purpose', models.ManyToManyField(to='common.purposes')),
                ('category', models.ManyToManyField(to='common.startappcategory')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
                'db_table': 'form',
            },
        ),
    ]
