# Generated by Django 5.1.6 on 2025-03-26 02:41

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_purposes_startappcategory_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('duration', models.CharField(max_length=256)),
                ('lesson_duration', models.CharField(max_length=256)),
                ('lesson_days', models.CharField(max_length=256)),
                ('age_limit', models.CharField(max_length=256)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[600, 600], upload_to='courses/%Y/%m')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'course',
            },
        ),
    ]
