# Generated by Django 5.1.6 on 2025-03-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=13)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course')),
            ],
            options={
                'verbose_name': 'CourseContact',
                'verbose_name_plural': 'CourseContacts',
                'db_table': 'CourseContact',
            },
        ),
    ]
