# Generated by Django 5.1.6 on 2025-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriveContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'SeriveContact',
                'verbose_name_plural': 'SeriveContacts',
                'db_table': 'SeriveContact',
            },
        ),
    ]
