# Generated by Django 5.1.7 on 2025-04-06 06:51

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_serivecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[330, 530], upload_to='serviceproduct/%Y/%m')),
            ],
            options={
                'verbose_name': 'ItProduct',
                'verbose_name_plural': 'ItProducts',
                'db_table': 'ItProduct',
            },
        ),
        migrations.CreateModel(
            name='ItSeriveContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'ItSeriveContact',
                'verbose_name_plural': 'ItSeriveContacts',
                'db_table': 'ItSeriveContact',
            },
        ),
        migrations.CreateModel(
            name='ItService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[456, 474], upload_to='services/%Y/%m')),
            ],
            options={
                'verbose_name': 'ItService',
                'verbose_name_plural': 'ItServices',
                'db_table': 'ItService',
            },
        ),
        migrations.CreateModel(
            name='ItServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'ItServiceType',
                'verbose_name_plural': 'ItServiceType',
                'db_table': 'ItServiceType',
            },
        ),
    ]
