# Generated by Django 5.1.6 on 2025-04-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_itproduct_itserivecontact_itservice_itservicetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItSeriveContact',
            new_name='ItServiceContact',
        ),
        migrations.RenameModel(
            old_name='SeriveContact',
            new_name='ServiceContact',
        ),
        migrations.AlterModelOptions(
            name='servicecontact',
            options={'verbose_name': 'ServiceContact', 'verbose_name_plural': 'ServiceContacts'},
        ),
        migrations.AlterModelTable(
            name='servicecontact',
            table='ServiceContact',
        ),
    ]
